<?php

namespace Santwer\DeveloperAnalyst\Dashboard\Http\Models;

use Illuminate\Database\Eloquent\Model;

class GitStatistics extends Model
{
	protected $fillable = ['user_id', 'date', 'commits', 'files', 'lines_of_code'];


	protected $casts = [
		'date' => 'date',
		'updated_at' => 'datetime',
		'created_at' => 'datetime',
	];

	protected $table = 'git_statistics';


	public function getConnectionName()
	{
		return config('developerAnalyst.connection');
	}

	public function getTable()
	{
		return config('developerAnalyst.database_table_prefix').parent::getTable(); // TODO: Change the autogenerated stub
	}
}
